### ISSUE TITLE
Validation for selectable fields

### ISSUE THREAD

**Issue by WellingtonCosta** [WellingtonCosta/convalida#1]
This feature will provide annotations to validate selectable fields, such as checkboxes and radio groups.

**Comment by hamedsilver** [comment]
checkboxes validation?

**Comment by WellingtonCosta** [comment]
@hamedsilver yes. Checkboxes and radio button validations.

**Comment by hamedsilver** [comment]
@WellingtonCosta how can i validate checkBoxes?

**Comment by WellingtonCosta** [comment]
Hi @hamedsilver 

I am working on this feature yet.

Basically, the developer will annotate any selectable fields (radio button, radio group, checkbox) with @CheckValidation and it will validate if the field is checked.

**Comment by ParitoshVaidya** [comment]
How to do it in XML layout while using data binding?
