### ISSUE TITLE
Anko support

### ISSUE THREAD

**Issue by fmatosqg** [WellingtonCosta/convalida#23]
Hi,

Any ideas on how to plug it with Kotlin Anko library? I tend to use it and skip data binding, so not sure how I'd put the annotations.

**Comment by WellingtonCosta** [comment]
Hi, @fmatosqg. It seems like a good idea, but I never worked with Anko and  don't quite know how it works, but I will learn more about it and analyse if is possible to provide support to use the Convalida with Anko.

**Comment by WellingtonCosta** [comment]
I was sawing the Anko example on the GitHub repository: 

```kotlin
verticalLayout {
    val name = editText()
    button("Say Hello") {
        onClick { toast("Hello, ${name.text}!") }
    }
}
```

And I think the solution below works:

```kotlin
@RequiredValidation
lateinit var name: EditText

@ValidateOnClick
lateinit var validateButton: Button

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    verticalLayout {
        name = editText()
        validateButton = button("Say Hello")
    }

    SampleActiityFieldsValidation.init(this) // the generated class
}

@OnValidationSuccess
fun success() = Toast.makeText(this, "${name.text}", Toast.LENGTH_LONG).show()
```

Can you try it?
