### ISSUE TITLE
CPF validation

### ISSUE THREAD

**Issue by PriscyllaT** [WellingtonCosta/convalida#24]
Hello @WellingtonCosta,

Does your library support CPF(Brazil personal number) validation?
If not, it would be awesome to have this available in your library.

Thanks,

**Comment by WellingtonCosta** [comment]
Hi @PriscyllaT

Nice idea! I'll implement it ASAP. :)

**Comment by WellingtonCosta** [comment]
Avaiable from the version 2.0.2.
