### ISSUE TITLE
Not require validation when field is blank

### ISSUE THREAD

**Issue by PriscyllaT** [WellingtonCosta/convalida#33]
Hey @WellingtonCosta ,

You could enhance you validations making them to validate fields, but not require the validation when field is blank, for example validate an e-mail but let users save the field if it is blank.

**Comment by WellingtonCosta** [comment]
Ok. I'll create a parameter called ```required``` with default value will be ```true``` in ```EmailValidator```, ```LengthValidator```, ```OnlyNumberValidator```, ```PatternValidator```, ```CpfValidator``` and in the new validations suggested in #32 and #31.

**Comment by WellingtonCosta** [comment]
Implemented and it will be available in release 2.2.0.
