### ISSUE TITLE
Publish sources of your artifacts to jitpack

### ISSUE THREAD

**Issue by Adonai** [WellingtonCosta/convalida#4]
When I click "Download sources" while looking through your library code Android Studio says sources cannot be found. It'd be very helpful if they were.

**Comment by WellingtonCosta** [comment]
You can download the sources by clicking on "Clone or Donwload" button.

**Comment by Adonai** [comment]
I know. But they are not downloaded and integrated with Android Studio this way.

Please publish them as maven sources.jar artifact.
Jitpack definitely supports this: https://jitpack.io/docs/#publishing-on-jitpack

**Comment by WellingtonCosta** [comment]
I don't see any motivation to do that. You can download the sources as zip archive or clone the repository.
