### ISSUE TITLE
Implement CNPJ validation

### ISSUE THREAD

**Issue by ivocoelho** [WellingtonCosta/convalida#47]
Something like this:
https://gist.github.com/AllanHasegawa/018ecd88605d7003c66fba89dfca8166

**Comment by WellingtonCosta** [comment]
Hi @ivocoelho 

We will implement this validation and it will be available in release 3.1.0.

**Comment by WellingtonCosta** [comment]
Done ([`5b49be`](https://github.com/WellingtonCosta/convalida/commit/5b49be576d5aa8cc6c4e72e7915615890bd9fb9f))
