### ISSUE TITLE
Add ability to validate input fields after they are unfocused

### ISSUE THREAD

**Issue by Adonai** [WellingtonCosta/convalida#5]
Just my 5 cents. Users actually don't want words "Invalid email!" come screaming at them when they just typed 1 letter.

It would be great if there'd be a way to support validate-on-unfocus pattern.

**Comment by WellingtonCosta** [comment]
Thanks for the tips. I implemented the validations based on the Google Material Design Error Pattern specification.

But your suggestion is interesting.

**Comment by emanuelet** [comment]
Actually the say "Show error text only after user interaction with a field."

https://material.io/guidelines/patterns/errors.html#errors-user-input-errors
